name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Bootstrap Terraform State Bucket
        run: |
          BUCKET_NAME="${{ secrets.TF_STATE_BUCKET }}"
          echo "Checking if S3 bucket '$BUCKET_NAME' exists..."
          if ! aws s3 ls "s3://$BUCKET_NAME" 2>&1 > /dev/null; then
            echo "Bucket does not exist. Creating..."
            aws s3 mb "s3://$BUCKET_NAME" --region us-east-1
          else
            echo "Bucket already exists."
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: infra/terraform/kubernetes
        run: |
          cat <<EOF > backend.tfbackend
          bucket = "${{ secrets.TF_STATE_BUCKET }}"
          key    = "terraform.tfstate"
          region = "us-east-1"
          EOF
          terraform init -backend-config=backend.tfbackend

      - name: Terraform Destroy
        working-directory: infra/terraform/kubernetes
        run: terraform destroy -var="tf_state_bucket=${{ secrets.TF_STATE_BUCKET }}" -auto-approve

      - name: Delete Terraform State Bucket
        if: always()
        run: |
          BUCKET_NAME="${{ secrets.TF_STATE_BUCKET }}"
          echo "Emptying and deleting S3 bucket '$BUCKET_NAME'..."
          aws s3 rm "s3://$BUCKET_NAME" --recursive
          aws s3 rb "s3://$BUCKET_NAME"
          echo "Bucket deleted."
